name: Report

options:
  bundleIdPrefix: dev.jano.report
  usesTabs: false
  indentWidth: 4
  tabWidth: 4
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 15.4

settings:
  CODE_SIGN_IDENTITY: iPhone Developer
  CODE_SIGN_STYLE: Automatic
  DEVELOPMENT_TEAM: PPSF6CNP8Q
  # Mac Catalyst support
  DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
  SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
  SUPPORTS_MACCATALYST: NO
  DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
  # Compiler
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
  DEAD_CODE_STRIPPING: YES

targets:

  Report:
    deploymentTarget:
      iOS: 15.4
    type: framework
    platform: iOS
    postCompileScripts:
      - script: swiftlint
        name: Swiftlint
    scheme:
      testTargets:
         - name: ReportTests
    settings:
       CURRENT_PROJECT_VERSION: 1
       INFOPLIST_FILE: targets/main/Info.plist
       IPHONEOS_DEPLOYMENT_TARGET: 15.4
       PRODUCT_BUNDLE_IDENTIFIER: dev.jano.report
       PRODUCT_NAME: Report
       TARGETED_DEVICE_FAMILY: 1
       SUPPORTS_MACCATALYST: NO
    sources: sources/main
    type: framework

  ReportTests:
    deploymentTarget:
      iOS: 15.4
    dependencies:
      - target: Report
    platform: iOS
    type: bundle.unit-test
    scheme:
      gatherCoverageData: true
      testTargets: 
        - name: ReportTests
    settings:
      INFOPLIST_FILE: targets/tests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: dev.jano.report.tests
    sources:
      - sources/tests
